
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-07T12:04:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "00c789308356f19b9b1e4a1a0708e56b7be62acb",
 "version": "0.7.1.post.dev596"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
