[tool.poetry]
name = "senfoni"
version = "0.0.1"
description = ""
authors = ["rcmalli <refikcanmalli@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
