
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-06T15:36:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1b3675c3b1e467c4d131e06c7a66338de56b7c42",
 "version": "0.2.4.post0.dev24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
