[tool.poetry]
name = "deiteo-kafka-client"
version = "0.0.2-alpha.0"
description = "Python Kafka Client Developed By Deiteo Organisation"
authors = ["Simon Thelin"]
readme = "README.md"
homepage = "https://github.com/deiteo/deiteo-kafka-client"
repository = "https://github.com/deiteo/deiteo-kafka-client"
packages = [
    { include = "**/*.*", from="src"}
]

[tool.poetry.dependencies]
python = "^3.8"
aiokafka = "0.7.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
ipdb = "^0.13.9"
pytest-cov = "^2.12.1"
pytest-asyncio = "0.18.3"
pre-commit = "^2.13.1"
wily = "1.20.0"
freezegun = "1.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
