[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quote-ondemand"
version = "1.0.0"
description = "Get the quote from internet"
readme = "README.md"
authors = [{ name = "Anuj Sadani", email = "anujsadani@infrrd.ai" }]
license = { file = "LICENSE" }
classifiers = [
   "License :: OSI Approved :: MIT License",
   "Programming Language :: Python :: 3",
]
keywords = ["quote", "tutorial", "random"]
dependencies = [
   "requests>=2.22.0",
   'tomli; python_version < "3.11"',
]
requires-python = ">=3.0"

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[project.urls]
Homepage = "https://github.com/anuj-sadani-infrrd/quote-ondemand"

[project.scripts]
quote = "quoteondemand.__main__:main"