
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-08T13:25:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "064e72f4c37d069dbb5e829e38cf196d32c89fa8",
 "version": "2.7.1.dev20220609"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
