#-->> System <<--------------------------------------------
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

#-->> Metadata <<------------------------------------------
[tool.poetry]
name        = "poetry-plugin-exe"
version     = "0.0.1"
description = "Poetry plugin to execute commands and/or scripts"
authors     = ["Christian Wiche <cwichel@gmail.com>"]
maintainers = ["Christian Wiche <cwichel@gmail.com>"]
license     = "license"
readme      = "readme.md"
keywords    = ["python", "utilities"]
homepage    = "https://github.com/cwichel/poetry-plugin-exe"
repository  = "https://github.com/cwichel/poetry-plugin-exe"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Build Tools",
]

#-->> Build & Dependencies <<------------------------------
# Main dependencies (required by application)
[tool.poetry.dependencies]
python              = "^3.7"
poetry              = "^1.2.0b1"

[tool.poetry.dev-dependencies]

#-->> Plugin & Script <<-----------------------------------
[tool.poetry.plugins."poetry.application.plugin"]
exe  = "poetry_plugin_exe:PoetryPluginExe"

[tool.poetry-plugin-exe.commands]
test = "TBD"
