[tool.poetry]
name = "gpd"
version = "1.1.1"
description = "Get a list of popular projects that use a library."

license = "MIT"
authors = ["Mislav Jaksic <jaksicmislav@gmail.com>"]
maintainers = []
readme = "README.md"

homepage = "https://github.com/MislavJaksic/get-popular-dependents"
repository = "https://github.com/MislavJaksic/get-popular-dependents"
documentation = "https://github.com/MislavJaksic/get-popular-dependents"

keywords = []

classifiers = []

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"
loguru = "^0.6.0"
bs4 = "^0.0.1"
pydantic = "^1.9.1"
tabulate = "^0.8.9"
tqdm = "^4.64.0"
diskcache = "^5.4.0"

[tool.poetry.dev-dependencies]
pytest-cov = "^3.0.0"
pytest = "^7.1.2"
pytest-asyncio = "^0.18.3"
pytest-integration = "0.2.2"
Sphinx = "^5.0.0"
black = "^22.3.0"
mypy = "^0.960"
types-tabulate = "^0.8.9"
types-requests = "^2.27.30"

[tool.poetry.scripts]
gpd = "gpd.runner:run"

[tool.mypy]
python_version = "3.8"
ignore_missing_imports = true
# plugins = pydantic.mypy

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = "tests"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
