
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-07T12:12:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "416f0b510af2f0e075bd07a7bde2ac7c6d3796cd",
 "version": "0.7.1.post.dev598"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
