
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-10T10:12:44-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "26e37d97675bd8793ee2feda301cd7f1516cd535",
 "version": "3.8.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
