[tool.poetry]
name = "stellar-contract-sdk"
version = "0.1.0.dev0"
description = "Python SDK for Stellar Smart Contracts"
authors = ["overcat <4catcode@gmail.com>"]
license = "Apache License 2.0"
packages = [
    { include = "src" },
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
