[build-system]
requires = [
    "hatchling>=1.3.1",
    "hatch-vcs"
]
build-backend = "hatchling.build"

[project]
name = "WebAppify"
description = "Create desktop apps of your favourite websites"
readme = "README.rst"
license = "MIT"
authors = [
    { name = "Raoul Snyman", email = "raoul@snyman.info" },
]
keywords = [
    "Qt",
    "website",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: MacOS X",
    "Environment :: Win32 (MS Windows)",
    "Environment :: X11 Applications",
    "Environment :: X11 Applications :: Qt",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Desktop Environment",
    "Topic :: Internet :: WWW/HTTP :: Browsers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "PyQt5",
    "PyQtWebEngine",
]
dynamic = [
    "version",
]

[project.urls]
Homepage = "https://git.snyman.info/raoul/webappify"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build]
include = [
    "/webappify",
]

[tool.hatch.build.targets.sdist]
[tool.hatch.build.targets.wheel]
