from enum import Enum


class StopReasonEnum(str, Enum):
    MANUAL = "MANUAL"
    MAX_EXECUTION_TIME_EXCEEDED = "MAX_EXECUTION_TIME_EXCEEDED"
    MISSING_HEARTBEAT = "MISSING_HEARTBEAT"
    FAILED_TO_START = "FAILED_TO_START"
    WORKFLOW_EXECUTION_STOPPED = "WORKFLOW_EXECUTION_STOPPED"
    WORKFLOW_EXECUTION_RETRIED = "WORKFLOW_EXECUTION_RETRIED"
    WORKFLOW_EXECUTION_TIMED_OUT = "WORKFLOW_EXECUTION_TIMED_OUT"

    def __str__(self) -> str:
        return str(self.value)
