[tool.poetry]
name = "convert-images"
version = "0.1.0"
description = "Simple CLI to convert images to JPEG and PNG format"
authors = ["Mohammad Alyetama <malyetama@pm.me>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
loguru = "^0.6.0"
Pillow = ">7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
cim = 'convert_images:convert_images.main'
