[build-system]
requires = [
	"setuptools",
	"setuptools-scm",
    "oldest-supported-numpy; python_version>='3.5'"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp3{8..11}-*"
skip = ["cp3{8..11}-mu*"]
