[tool.poetry]
name = "django3-leaf"
version = "3.0.1"
description = "Render and serve django templates based on URL."
homepage = "https://github.com/ImaginaryLandscape/django3-leaf"
readme = "README.md"
authors = ["Ryan Senkbeil <sysadmin@corecreative.com>"]
maintainers = ["Imagescape <info@imagescape.com>"]
license = "BSD"
packages = [
    { include = "leaf" },
]

[tool.poetry.dependencies]
python = "^3.7"
django-mptt = ">= 0.11.0"
six = ">= 1.16.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
