[project]
    name = "make_pdf"
    description = "A command line tool to convert files to fancy PDFs"
    authors = [{ "name" = "EorlBruder", "email" = "eorl@bruder.space" }]
    license = {"file" = "LICENSE"}
    readme = "README.md"
    requires-python = ">=3.6,<4"
    keywords = ["cli"]
    classifiers = [
        "Environment :: Console",
        "Development Status :: 2 - Pre-Alpha",
        "Intended Audience :: End Users/Desktop",
        "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
        "Natural Language :: English",
        "Operating System :: MacOS :: MacOS X",
        "Operating System :: POSIX",
        "Operating System :: POSIX :: BSD",
        "Operating System :: POSIX :: Linux",
        "Operating System :: Microsoft :: Windows",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Topic :: Text Processing",
    ]
    dependencies = [
        "pypandoc >=1.6,<2",
        "click >=8,<9",
        "appdirs >=1.4,<2"
    ]
    dynamic = ['version']

[project.urls]
    Homepage = "https://make-pdf.de/"
    Source = "https://git.eorlbruder.de/EorlBruder/make_pdf"
    Documentation = "https://make-pdf.de/"

[project.scripts]
    make_pdf = "make_pdf:cli"

[project.optional-dependencies]
    test = ["pytest >=6.2.4,<7","pytest-mock >=3.6,<4"]
    changelog = ["towncrier >=21.3,<22"]
    dev = ["black[d] >=21.4b0,<22", "babel >=2.7,<3"]
    doc = ["sphinx >=4.1,<5", "sphinx-intl >=2,<3"]
    publish = ["flit >=3.3,<4"]

[build-system]
    requires = ["flit_core >=3.2,<4"]
    build-backend = "flit_core.buildapi"

[tool.pytest.ini_options]
    minversion = "6.0"
    testpaths = ["tests"]

[tool.towncrier]
    package = "changes"
    package_dir = ""
    filename = "CHANGELOG"
    directory = "changes/changelog.d/"
    start_string = ".. towncrier\n"
    template = "changes/template.rst"
    issue_format = ""
    title_format = "{version} (unreleased)"
    underlines = "-"

    [[tool.towncrier.section]]
        path = ""

    [[tool.towncrier.type]]
        directory = "feature"
        name = "Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "enhancement"
        name = "Enhancements"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bugfixes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "doc"
        name = "Documentation"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "i18n"
        name = "i18n"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "misc"
        name = "Other"
        showcontent = true

[tool.black]
    line-length = 120
    target-version = ['py36']
    include = '\.pyi?$'