[tool.poetry]
authors = ["Daniel Schmidt <danischm@cisco.com>"]
description = "A CLI tool to perform syntactic and semantic validation of YAML files."
documentation = "https://github.com/netascode/iac-validate"
homepage = "https://github.com/netascode/iac-validate"
license = "LICENSE"
maintainers = ["Daniel Schmidt <danischm@cisco.com>"]
name = "iac-validate"
readme = "README.md"
repository = "https://github.com/netascode/iac-validate"
version = "0.1.2"

[tool.poetry.scripts]
iac-validate = "iac_validate.cli.main:main"

[tool.poetry.dependencies]
click = "^8.0.4"
errorhandler = "^2.0.1"
importlib-metadata = {version = "^2.0.0", python = "<3.8"}
python = "^3.6"
"ruamel.yaml" = "^0.16.10"
yamale = "^4.0.3"

[tool.poetry.dev-dependencies]
black = [
  {version = "^20.8b1", python = "<3.7"},
  {version = "^21.12b0", python = "^3.7"},
]
flake8 = "^3.7.9"
isort = "^5.2.2"
mypy = "^0.960"
pre-commit = {version = "^2.2.0", python = ">=3.7"}
pytest = "^6.1.2"
pytest-cov = "^2.8.1"
pytest-mock = "^3.0.0"
toml = "^0.10.0"

[tool.coverage.run]
source = ["iac_validate"]

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "@abstract", "except ImportError:"]
omit = ["*/__main__.py"]

[tool.isort]
# https://github.com/timothycrosley/isort
# https://github.com/timothycrosley/isort/wiki/isort-Settings
# splits long import on multiple lines indented by 4 spaces
force_grid_wrap = 0
include_trailing_comma = true
indent = "    "
line_length = 88
multi_line_output = 3
use_parentheses = true
# will group `import x` and `from x import` of the same module.
combine_as_imports = true
default_section = "THIRDPARTY"
force_sort_within_sections = true
forced_separate = "tests"
known_first_party = ["iac_validate", "tests"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.pytest.ini_options]
markers = ["unit", "integration"]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry_core>=1.0.0"]
