# Generated by Django 3.2.6 on 2022-03-04 11:26

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Идентификатор накладной в ФЗ'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sended',
            field=models.BooleanField(default=False, verbose_name='Передан в ФармЗаказ'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sended_at',
            field=models.DateTimeField(null=True, verbose_name='Время отправки в ФЗ'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='warehouse_ext_id',
            field=models.CharField(default=None, max_length=100, verbose_name='Уникальный идентификатор склада в системе дистрибьютора'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_num',
            field=models.CharField(max_length=30, verbose_name='Номер накладной'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='sended_at',
            field=models.DateTimeField(null=True, verbose_name='Время отправки в ФЗ'),
        ),
        migrations.AlterField(
            model_name='orderstatusmap',
            name='status_pharm_zakaz',
            field=models.CharField(choices=[('new', 'Новый'), ('transmitted', 'ПолученДистрибьютором'), ('confirmed', 'Подтвержден'), ('assembly', 'ПереданНаСборку'), ('equipped', 'Укомплектован'), ('sent', 'Отправлен'), ('delivered', 'Доставлен'), ('canceled', 'Отменен'), ('blocked', 'Заблокирован'), ('refund', 'Возврат')], max_length=30, verbose_name='Статус заказа в ФармЗаказ'),
        ),
        migrations.AlterField(
            model_name='position',
            name='series',
            field=models.CharField(blank=True, help_text='Указывается номер серии товара, для которой явным образом указана дата производства и дата истечения срока годности, example: 040721', max_length=50, null=True, verbose_name='Номер серии товара.'),
        ),
        migrations.AlterField(
            model_name='residue',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='Дата окончания срока годности'),
        ),
        migrations.AlterField(
            model_name='residuehistory',
            name='expiration_date',
            field=models.DateField(verbose_name='Дата окончания срока годности'),
        ),
        migrations.AlterField(
            model_name='store',
            name='sended_at',
            field=models.DateTimeField(null=True, verbose_name='Время отправки в ФЗ'),
        ),
    ]
