# Generated by Django 3.2.6 on 2022-03-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_kafkaoffset_client_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalentity',
            options={'verbose_name': 'Запрос юридических лиц', 'verbose_name_plural': 'Запросы юридических лиц'},
        ),
        migrations.AlterModelOptions(
            name='legalentityonboarded',
            options={'verbose_name': 'Одобренные запросы юридических лиц', 'verbose_name_plural': 'Одобренные запросы юридических лиц'},
        ),
        migrations.AlterField(
            model_name='legalentityonboarded',
            name='ext_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Идентификатор на стороне 1С'),
        ),
        migrations.AlterField(
            model_name='legalentityonboarded',
            name='inn',
            field=models.CharField(max_length=255, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='legalentityonboarded',
            name='pharm_zakaz_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Идентификатор на стороне ФАРМЗАКАЗА'),
        ),
        migrations.AlterField(
            model_name='legalentityonboarded',
            name='sended_to_pz',
            field=models.BooleanField(default=False, editable=False, verbose_name='Отправлено в ФАРМЗАКАЗ?'),
        ),
        migrations.AlterField(
            model_name='legalentityonboarded',
            name='sended_to_pz_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Последняя дата отправки в ФАРМЗАКАЗ'),
        ),
    ]
