# Generated by Django 3.2.6 on 2022-04-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reconciliationresidue'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationresidue',
            name='uid_reconciliation',
            field=models.CharField(max_length=100, null=True, verbose_name='Идентификатор группы сверки остатков'),
        ),
    ]
