# Generated by Django 3.2.6 on 2022-05-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_branch_target_topic_to_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='target_topic_to_send',
            field=models.CharField(max_length=255, verbose_name='Название топика для отправки'),
        ),
    ]
