
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-07T11:35:38-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f17c7165adc05688a092e963c3fa67707b9680bc",
 "version": "2022.6.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
