
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-12T14:44:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "71b9a47d0759a315847a21bee39e8b1d18b92c0f",
 "version": "0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
