---
$schema: https://json-schema.org/draft/2020-12/schema
$id: laboro.config.workflow.schema
title: Laboro workflow
description: Laboro worflow
type: object
properties:
  laboro:
    type: object
    properties:
      workflow:
        type: object
        properties:
          name:
            type: string
          packages:
            $schema: https://json-schema.org/draft/2020-12/schema
            $id: laboro.config.workflow.package.schema
            title: Laboro workflow package
            description: Laboro worflow package
            type: array
            items:
              type: string
          steps:
            $schema: https://json-schema.org/draft/2020-12/schema
            $id: laboro.config.workflow.step.schema
            title: Laboro workflow step
            description: Laboro worflow step
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                module:
                  $schema: https://json-schema.org/draft/2020-12/schema
                  $id: laboro.config.workflow.step.module.schema
                  title: Laboro workflow step module
                  description: Laboro worflow step module
                  type: object
                  properties:
                    name:
                      type: string
                    class:
                      type: string
                    args:
                      type: object
                    actions:
                      $schema: https://json-schema.org/draft/2020-12/schema
                      $id: laboro.config.workflow.step.action.schema
                      title: Laboro workflow action
                      description: Laboro worflow action
                      type: array
                      items:
                        type: object
                        properties:
                          method:
                            type: string
                          args:
                            type: object
                          output:
                            type: object
                            properties:
                              type:
                                type:
                                  - string
                                  - "null"
                                enum:
                                  - memory
                                  - file
                                  - null
                              value:
                                type:
                                  - string
                            anyOf:
                              - not:
                                  properties:
                                    type:
                                      type: string
                                  required:
                                    - type
                              - required:
                                  - value
                            additionalProperties: False
                        required:
                          - method
                          - args
                          - output
                        additionalProperties: False
                  required:
                    - name
                    - class
                    - args
                    - actions
                  additionalProperties: False
              required:
                - name
                - module
              additionalProperties: False
        required:
          - name
          - packages
          - steps
        additionalProperties: False
required:
  - laboro
additionalProperties: False
