[tool.poetry]
name = "sciops"
version = "0.1.0"
description = "Collection of utilities for scientific operations"
authors = ["Dylan Miracle <dylan.miracle@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
rich = "^12.4.4"
pytest = "^7.1.2"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
