[tool.poetry]
name = "clscurves"
version = "0.0.3"
description = "Compute and plot bootstrapped performance curves for classification problems."
authors = ["Christopher Bryant <cbryant@berkeley.edu>"]
maintainers = ["Christopher Bryant <cbryant@berkeley.edu>"]
readme = "README.md"
repository = "https://github.com/chrismbryant/classification-curves"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
numpy = "^1.20.3"
pandas = "^1.2.4"
matplotlib = "^3.4.2"
scipy = "^1.6.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
flake8 = "^3.9.2"
Sphinx = "^3.5.4"
numpydoc = "^1.1.0"
jinja2 = "<3.1"
furo = "^2021.4.11-beta.34"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
