
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-06T19:26:14-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "39cd855f7d9313e6efac33147963b81f8b8dd28a",
 "version": "2.4.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
