[tool.poetry]
name = "splink"
version = "2.1.14"
description = "Implementation of Fellegi-Sunter's canonical model of record linkage in Apache Spark, including EM algorithm to estimate parameters"
authors = ["Robin Linacre <robinlinacre@hotmail.com>", "Sam Lindsay", "Theodore Manassis"]
license = "MIT"
homepage = "https://github.com/moj-analytical-services/splink"
repository = "https://github.com/moj-analytical-services/splink"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
jsonschema = "^3.2"
typeguard = "^2.10.0"
sqlglot = "1.23.1"

[tool.poetry.dev-dependencies]
pytest = "^5.3"
pandas = "^1.0.0"
splink-data-generation = "^1.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
