[tool.poetry]
name = "sls-json-fast"
version = "0.1.2"
description = "aliyun sls log python for json"
readme = "README.md"
authors = ["JimZhang <zzl22100048@gmail.com>"]
[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
[tool.poetry.dependencies]
python = "^3.6"
aliyun-log-python-sdk = "^0.7"
protobuf="^3.4.0"
[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
