
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-09T15:39:57-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2e78e60cf9782bf96afc0fcf74bcfe7d31b84ba",
 "version": "v1.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
