# Generated by Django 3.2.6 on 2022-06-03 08:28

from django.conf import settings
from django.db.models.deletion import CASCADE
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=50, verbose_name='Система')),
                ('api_method', models.CharField(blank=True, help_text='<strong>Пример:</strong> <em>GET https://demo.pharm-zakaz.ru/api/distributor/v1/stores/</em>', max_length=255, verbose_name='API метод')),
                ('limit', models.IntegerField(blank=True, help_text='Максимальное количество запросов за временной интервал', null=True, verbose_name='Количество запросов')),
                ('window', models.IntegerField(blank=True, help_text='Интервал в котором будут считаться запросы для limit', null=True, verbose_name='Временной интервал в секундах')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
