
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-10T19:14:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1f7aa5ed3ea7d602458633e5de69dd733fd90916",
 "version": "0.2.5.post0.dev36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
