# Generated by Django 3.2.6 on 2022-03-18 06:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220304_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('client_type', models.CharField(choices=[(1, 'Consumer'), (2, 'Producer')], max_length=30, verbose_name='Тип')),
                ('topic', models.CharField(max_length=120, verbose_name='Имя топика')),
                ('offset', models.IntegerField(verbose_name='Смещение')),
                ('partition', models.IntegerField(verbose_name='Партиция')),
            ],
            options={
                'verbose_name': 'Смещение сообщений кафки',
                'verbose_name_plural': 'Смещение сообщений кафки',
            },
        ),
        migrations.AddField(
            model_name='kafkamsg',
            name='data_key',
            field=models.CharField(max_length=120, verbose_name='Ключ данных'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kafkamsg',
            name='dict_obj',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='kafkamsg',
            name='recipient',
            field=models.CharField(max_length=120, verbose_name='Получатель'),
            preserve_default=False,
        ),
    ]
