# Generated by Django 3.2.6 on 2022-03-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220325_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHandlersMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_handler', models.CharField(max_length=120, verbose_name='Имя обработчика')),
                ('topic', models.CharField(max_length=120, verbose_name='Имя топика')),
            ],
            options={
                'verbose_name': 'Соответствие топика и обработчика',
                'verbose_name_plural': 'Соответствие топика и обработчика',
            },
        ),
        migrations.AlterModelOptions(
            name='legalentity',
            options={'verbose_name': 'Запрос юридических лиц', 'verbose_name_plural': 'Запросы юридических лиц'},
        ),
        migrations.AlterModelOptions(
            name='legalentityonboarded',
            options={'verbose_name': 'Запись о контракте с юр.лицом', 'verbose_name_plural': 'Записи о контракте с юр.лицом'},
        ),
    ]
