# Generated by Django 3.2.6 on 2022-05-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reconciliationresidue_uid_reconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100, verbose_name='Имя атрибута')),
                ('attribute_value', models.CharField(help_text='Для булева значения используется True/False', max_length=255, verbose_name='Значение атрибута')),
                ('attribute_type', models.CharField(choices=[('str', 'Строка'), ('int', 'Целое число'), ('float', 'Число с плавающей точкой'), ('bool', 'Булево')], max_length=255, verbose_name='Тип атрибута')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
