[tool.poetry]
name = "exaroton"
version = "0.0.3"
description = "Python API wrapper for exaroton"
authors = ["Colin <colin@colinshark.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.28.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
