[tool.poetry]
name = "munchie"
version = "0.1.3"
description = "Compilation of commonly used functionality in personal projects"
authors = ["Anthony Gaetano <adgaetano@gmail.com>"]
readme = "README.md"
classifiers=[
    "Development Status :: 1 - Planning",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Operating System :: MacOS :: MacOS X",
]
license = "Apache License 2.0"

[tool.poetry.dependencies]
python = "3.10"
toml = "^0.10.2"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
pytest = "^7.1.2"
pytest-sugar = "^0.9.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
