[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[project]
name = "micoda"
requires-python = ">=3.8"
description = "A Python module to parse Markdown. Powered by `PyO3` and `pulldown-cmark`."
readme = "README.md"
authors = [
    {email = "shengurun@gmail.com"},
    {name = "shengurun"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[tool.maturin]
bindings = "pyo3"
