
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-12T18:39:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "19af39959baa34eea4a34aa564945a0cbef30f62",
 "version": "0.0.4rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
