# coding: utf-8

"""
    InsightsServices-Dev-QA

    SR Insight Service API Documentation  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import insights-plotrisk
from insights-plotrisk.api.generic_o_data_controller_api import GenericODataControllerApi  # noqa: E501
from insights-plotrisk.rest import ApiException


class TestGenericODataControllerApi(unittest.TestCase):
    """GenericODataControllerApi unit test stubs"""

    def setUp(self):
        self.api = insights-plotrisk.api.generic_o_data_controller_api.GenericODataControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_process_using_get(self):
        """Test case for process_using_get

        process  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
