# coding: utf-8

"""
    InsightsServices-Dev-QA

    SR Insight Service API Documentation  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import insights-plotrisk
from insights-plotrisk.models.feature_collection_req import FeatureCollectionReq  # noqa: E501
from insights-plotrisk.rest import ApiException


class TestFeatureCollectionReq(unittest.TestCase):
    """FeatureCollectionReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeatureCollectionReq(self):
        """Test FeatureCollectionReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = insights-plotrisk.models.feature_collection_req.FeatureCollectionReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
