[tool.poetry]
name = "grimoirelab"
version = "0.3.0"
description = "Tool set for software development analytics"
authors = [
    "GrimoireLab Developers"
]
license = "GPL-3.0+"

readme = "README.md"

homepage = "https://chaoss.github.io/grimoirelab/"
repository = "https://github.com/chaoss/grimoirelab"

keywords = [
    "development",
    "grimoirelab"
]

packages = [
    { include = "grimoirelab" }
]

classifiers = [
   "Development Status :: 5 - Production/Stable",
   "Intended Audience :: Developers",
   "Topic :: Software Development",
   "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
   "Programming Language :: Python :: 3"
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/chaoss/grimoirelab/issues"

[tool.poetry.scripts]
'grimoirelab' = 'grimoirelab.grimoirelab:main'

[tool.poetry.dependencies]
python = "^3.7"

grimoirelab-toolkit = "^0.3.0"
perceval = "^0.18.0"
perceval-mozilla = "^0.3.0"
perceval-opnfv = "^0.2.0"
perceval-puppet = "^0.2.0"
perceval-weblate = "^0.2.0"
kingarthur = "^0.2.0"
sortinghat = "^0.7.20"
kidash = "^0.5.0"
grimoirelab-panels = "^0.1.0"
grimoire-elk = "^0.101.1"
sirmordred = "^0.3.0"
cereslib = "^0.3.0"
graal = "^0.3.0"
statsmodels = "^0.13.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
