
[tool.isort]
profile = "black"
skip_gitignore = "True"
line_length = 119

[tool.black]
line-length = 119
target-version = ['py38']

[tool.poetry]
name = "pydacharts"
version = "0.1.2"
description = ""
authors = ["Josh Brooks <josh@catalpa.io>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.9.0"
pytest-cov = "^3.0.0"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^22.1.0"
mypy = "^0.931"
flake8 = "^4.0.1"
pytest = "^7.0.1"
Flask = "^2.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
