[tool.poetry]
name = "adranis-sigma"
version = "0.1.0"
description = "Firt release of the python binding of the Adranis Sigma API"
authors = ["Adranis GmbH <contact@adranis.ch>"]
license = "BSD 2-Clause License"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
scipy = "^1.8.1"
numpy = "^1.22.4"
appdirs = "^1.4.4"
pandas = "^1.4.2"
plotly = "^5.8.2"


[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
coverage = "^6.4.1"
mypy = "^0.961"
pre-commit = "^2.19.0"
yapf = "^0.32.0"
Sphinx = "^5.0.1"
furo = "^2022.6.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
