[tool.poetry]
name = "func_adl_servicex_xaodr21"
version = "1.1.4.21.2.209"
description = "func-adl typed datasets for Servicex for xAOD R21 21.2.209"
authors = ["Gordon Watts <gwatts@uw.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
func_adl_servicex = {version = "^2.0-beta.1", allow-prereleases = true}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
