
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-08T12:38:35-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6223c5d916776021c887cc5bc1c18620929eed71",
 "version": "7.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
