[tool.poetry]
name = "pysignald-async"
version = "0.2"
description = "Python bindings for signald"
authors = ["Nicolas Cedilnik <nicoco@nicoco.fr>"]
readme = "README.rst"
homepage = "https://gitlab.com/nicocool84/pysignald-async"

[tool.poetry.dependencies]
python = "^3.7"
aiosignald = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
