[tool.poetry]
name = "gen_changelog"
version = "0.1.0"
description = "A very simple script to generate a changelog from a repo with Conventional-Commits-compatible commit messages."
authors = ["Stavros Korokithakis <hi@stavros.io>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.8"
GitPython = "^3.1.24"

[tool.poetry.scripts]
gen_changelog = "gen_changelog.cli:cli"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
