[project]
requires-python = ">=3.7"

[build-system]
requires = ["setuptools >= 40.6.0", "pybind11 >= 2.6.0", "ducc0", "matplotlib", "h5py", "mpi4py", "python-casacore", "scipy", "nifty8"]
build-backend = "setuptools.build_meta"
