[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quote-ondemand"
version = "1.0.1"
description = "Get the quote from internet"
readme = "README.md"
authors = [{ name = "Anuj Sadani", email = "anuj.k.sadani@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
   "License :: OSI Approved :: MIT License",
   "Programming Language :: Python :: 3",
]
keywords = ["quote", "tutorial", "random"]
dependencies = [
   "requests>=2.22.0",
]
requires-python = ">=3.0"

[project.urls]
Homepage = "https://github.com/anuj-sadani-infrrd/quote-ondemand"

[project.scripts]
quote = "quoteondemand.__main__:main"