jobs:
- job:
  displayName: ubuntu-18.04-38
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name bw2
    displayName: Create Anaconda environment

  - bash: |
      source activate bw2
      conda install --yes --quiet -c defaults -c conda-forge -c cmutel -c haasad --name bw2 bw_processing python=$PYTHON_VERSION pytest peewee brightway2 bw_processing pytest pytest-azurepipelines pytest-cov pip bw_processing
    displayName: Install Anaconda packages

  - bash: |
      source activate bw2
      pytest --cov=bw2data
    displayName: pytest

- job:
  displayName: macOS-10.14-38
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      Python38:
        python.version: '3.8'
      Python37:
        python.version: '3.7'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name bw2
    displayName: Create Anaconda environment

  - bash: |
      source activate bw2
      conda install --yes -c defaults -c conda-forge -c cmutel -c haasad --name bw2 python=$PYTHON_VERSION bw_processing pytest peewee brightway2 bw_processing pytest pytest-azurepipelines pytest-cov pip bw_processing
    displayName: Install Anaconda packages

  - bash: |
      source activate bw2
      pytest --cov=bw2data
    displayName: pytest

- job:
  displayName: vs2017-win2016-38
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python38:
        python.version: '3.8'
      Python37:
        python.version: '3.7'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name bw2
    displayName: Create Anaconda environment

  - script: |
      call activate bw2
      conda install --yes -c defaults -c conda-forge -c cmutel -c haasad --name bw2 python=%PYTHON_VERSION% bw_processing pytest peewee brightway2 bw_processing pytest pytest-azurepipelines pytest-cov pywin32 pip bw_processing
    displayName: Install Anaconda packages

  - script: |
      call activate bw2
      pytest --cov=bw2data
    displayName: pytest
