[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pybay"
version = "1.0.0"
description = "Powerfull module to control bayfiles.com api using python"
readme = "README.md"
authors = [{ name = "vodkarm", email = "vodkarm06@gmail.com" }]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "requests"
]
requires-python = ">=3.9"

[project.optional-dependencies]
dev = ["vodkarm"]

[project.urls]
Homepage = "https://github.com/vodkarm/pybay"

[project.scripts]
realpython = "reader.__main__:main"