
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-09T10:34:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d1ba9f4f496c25959e6dbf71dca240ae8d5a0c56",
 "version": "1.12.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
