
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-13T18:45:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0452c8f0092324c38a0ccdd7229bf3579378680",
 "version": "3.0.0dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
