language: python
dist: xenial

env:
  global:
    - VIPS_VERSION_MAJOR=8
    - VIPS_VERSION_MINOR=9
    - VIPS_VERSION_MICRO=0
    - PATH=$HOME/vips/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
    - PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH

addons:
  apt:
    packages:
      - libexpat1-dev
      - gettext
      - liblcms2-dev
      - libmagickwand-dev
      - libopenexr-dev
      - libcfitsio3-dev
      - libfftw3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - librsvg2-dev
      - libwebp-dev
      - libtiff5-dev
      # missing on xenial, unfortunately
      # - libwebpmux2
      - libglib2.0-dev

cache:
  directories:
    - $HOME/vips

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
  - "pypy"
  - "pypy3"

# 3.3 is failing with some kind of setuptools issue
matrix:
  allow_failures:
    - python: "3.3" 
    - python: "3.7" 
    - python: "3.8" 
    - python: "nightly"

install:
  - pip install -U .[test]

script:
  - python setup.py test

# the vips7 py binding won't work with pypy, make sure it's off
before_install:
  - uname -a
  - bash install-vips.sh --without-python
  - pip install -U setuptools
