# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetNexusSecurityUserTokenResult',
    'AwaitableGetNexusSecurityUserTokenResult',
    'get_nexus_security_user_token',
]

@pulumi.output_type
class GetNexusSecurityUserTokenResult:
    """
    A collection of values returned by GetNexusSecurityUserToken.
    """
    def __init__(__self__, enabled=None, id=None, protect_content=None):
        if enabled and not isinstance(enabled, bool):
            raise TypeError("Expected argument 'enabled' to be a bool")
        pulumi.set(__self__, "enabled", enabled)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if protect_content and not isinstance(protect_content, bool):
            raise TypeError("Expected argument 'protect_content' to be a bool")
        pulumi.set(__self__, "protect_content", protect_content)

    @property
    @pulumi.getter
    def enabled(self) -> bool:
        return pulumi.get(self, "enabled")

    @property
    @pulumi.getter
    def id(self) -> str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="protectContent")
    def protect_content(self) -> bool:
        return pulumi.get(self, "protect_content")


class AwaitableGetNexusSecurityUserTokenResult(GetNexusSecurityUserTokenResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetNexusSecurityUserTokenResult(
            enabled=self.enabled,
            id=self.id,
            protect_content=self.protect_content)


def get_nexus_security_user_token(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetNexusSecurityUserTokenResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    if opts is None:
        opts = pulumi.InvokeOptions()
    if opts.version is None:
        opts.version = _utilities.get_version()
        if opts.plugin_download_url is None:
            opts.plugin_download_url = _utilities.get_plugin_download_url()
    __ret__ = pulumi.runtime.invoke('nexus:index/getNexusSecurityUserToken:GetNexusSecurityUserToken', __args__, opts=opts, typ=GetNexusSecurityUserTokenResult).value

    return AwaitableGetNexusSecurityUserTokenResult(
        enabled=__ret__.enabled,
        id=__ret__.id,
        protect_content=__ret__.protect_content)
