
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-13T20:07:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "74fb5433e4d3d5cefee4d7699932d748482f7b92",
 "version": "2.7.1.dev20220614"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
