# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LinStackNode.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12LinStackNode.proto\x12\x0cLinStackNode\x1a\x0c\x43ommon.proto\"1\n\x10lin_stack_config\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"C\n\x11lin_stack_configs\x12.\n\x06\x63onfig\x18\x01 \x03(\x0b\x32\x1e.LinStackNode.lin_stack_config\"V\n\x10lin_stack_status\x12\x1e\n\x06result\x18\x01 \x01(\x0b\x32\x0e.Common.result\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12\x12\n\nstr_status\x18\x03 \x01(\t2\x99\x02\n\x0cLinStackNode\x12(\n\x05Reset\x12\r.Common.empty\x1a\x0e.Common.result\"\x00\x12>\n\tSetConfig\x12\x1f.LinStackNode.lin_stack_configs\x1a\x0e.Common.result\"\x00\x12\x30\n\rStartLinStack\x12\r.Common.empty\x1a\x0e.Common.result\"\x00\x12/\n\x0cStopLinStack\x12\r.Common.empty\x1a\x0e.Common.result\"\x00\x12<\n\tGetStatus\x12\r.Common.empty\x1a\x1e.LinStackNode.lin_stack_status\"\x00\x62\x06proto3')



_LIN_STACK_CONFIG = DESCRIPTOR.message_types_by_name['lin_stack_config']
_LIN_STACK_CONFIGS = DESCRIPTOR.message_types_by_name['lin_stack_configs']
_LIN_STACK_STATUS = DESCRIPTOR.message_types_by_name['lin_stack_status']
lin_stack_config = _reflection.GeneratedProtocolMessageType('lin_stack_config', (_message.Message,), {
  'DESCRIPTOR' : _LIN_STACK_CONFIG,
  '__module__' : 'LinStackNode_pb2'
  # @@protoc_insertion_point(class_scope:LinStackNode.lin_stack_config)
  })
_sym_db.RegisterMessage(lin_stack_config)

lin_stack_configs = _reflection.GeneratedProtocolMessageType('lin_stack_configs', (_message.Message,), {
  'DESCRIPTOR' : _LIN_STACK_CONFIGS,
  '__module__' : 'LinStackNode_pb2'
  # @@protoc_insertion_point(class_scope:LinStackNode.lin_stack_configs)
  })
_sym_db.RegisterMessage(lin_stack_configs)

lin_stack_status = _reflection.GeneratedProtocolMessageType('lin_stack_status', (_message.Message,), {
  'DESCRIPTOR' : _LIN_STACK_STATUS,
  '__module__' : 'LinStackNode_pb2'
  # @@protoc_insertion_point(class_scope:LinStackNode.lin_stack_status)
  })
_sym_db.RegisterMessage(lin_stack_status)

_LINSTACKNODE = DESCRIPTOR.services_by_name['LinStackNode']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIN_STACK_CONFIG._serialized_start=50
  _LIN_STACK_CONFIG._serialized_end=99
  _LIN_STACK_CONFIGS._serialized_start=101
  _LIN_STACK_CONFIGS._serialized_end=168
  _LIN_STACK_STATUS._serialized_start=170
  _LIN_STACK_STATUS._serialized_end=256
  _LINSTACKNODE._serialized_start=259
  _LINSTACKNODE._serialized_end=540
# @@protoc_insertion_point(module_scope)
