# coding: utf-8

"""
    InsightsServices-Dev-QA

    SR Insight Service API Documentation  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import insights-plotrisk
from insights-plotrisk.models.multi_point import MultiPoint  # noqa: E501
from insights-plotrisk.rest import ApiException


class TestMultiPoint(unittest.TestCase):
    """MultiPoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiPoint(self):
        """Test MultiPoint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = insights-plotrisk.models.multi_point.MultiPoint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
