[tool.poetry]
name = "sync_back"
version = "0.2.1"
description = ""
authors = ["Deepio"]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
rich = "^12.4.4"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
Sphinx = "^5.0.0"
mistune = "0.8.4"
m2r2 = "^0.3.2"
coverage = "^6.4"

[tool.poetry.scripts]
bsync = "sync_back:term.cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
