
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-08T15:01:13+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6fa2a7883ebeda8c94e08b381038cbcadffc60b5",
 "version": "0.15.7a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
