[tool.poetry]
name = "resistant_documents_client"
version = "2.2.0"
description = "Resistant.ai document forjerry python client for convenient integration with REST API service."
authors = ["Resistant.ai <sales@resistant.ai>"]
readme = 'README.md'
include = ["resistant_documents_client/*.py"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22.0"
requests-oauthlib = {version = "^1.3.0"}

[tool.poetry.dev-dependencies]
pytest = "^6.0.0"
requests-mock = "^1.7.0"
freezegun = "^1.1.0"
