[build-system]
requires = ["setuptools",
            "wheel",
            "cython>=0.29.0",
            "numpy>=1.20.0",
            "tqdm",
            "pandas",
            "scipy"]
build-backend = "setuptools.build_meta"
