[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "i_xero2"
author = "Jason Romano"
author-email = "aracnid@gmail.com"
home-page = "https://github.com/aracnid/i-xero2"
classifiers = ["License :: Other/Proprietary License"]
description-file = "README.md"
requires-python = "~=3.10"
requires = [
    "aracnid-logger",
    "flask",
    "flask-oauthlib",
    "flask-session",
    "i-mongodb",
    "pytz",
    "xero-python"
]
keywords = "i-xero,xero,i-xero2"

[tools.flit.metadata.requires-extra]
build = ["flit"]
test = ["pytest"]

[tool.pytest.ini_options]
addopts = "-p no:warnings"
log_cli = true
log_cli_level = "DEBUG"
