
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-10T22:50:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "31a5c4f9a81ba6866b632bd93e7db6ccf08fc4da",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
