# Generated by Django 3.2.9 on 2022-06-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mad_notifications', '0014_auto_20220530_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationConfig',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('allow_email', models.BooleanField(default=True)),
                ('allow_push', models.BooleanField(default=True)),
                ('allow_sms', models.BooleanField(default=True)),
                ('allow_whatsapp', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
