# Generated by Django 3.2.6 on 2022-04-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220324_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalentityonboarded',
            options={'verbose_name': 'Одобренные запросы юридических лиц', 'verbose_name_plural': 'Одобренные запросы юридических лиц'},
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='sended_to_1c',
            field=models.BooleanField(default=False, verbose_name='Отправлено в 1C'),
        ),
        migrations.AlterField(
            model_name='legalentityonboarded',
            name='sended_to_pz',
            field=models.BooleanField(default=False, verbose_name='Отправлено в ФАРМЗАКАЗ?'),
        ),
        migrations.AlterField(
            model_name='legalentityonboarded',
            name='sended_to_pz_at',
            field=models.DateTimeField(null=True, verbose_name='Последняя дата отправки в ФАРМЗАКАЗ'),
        ),
    ]
