# Generated by Django 3.2.6 on 2022-04-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220401_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='info_received',
            field=models.BooleanField(default=False, verbose_name='Строка подтверждена 1С?'),
        ),
        migrations.AlterField(
            model_name='legalentityonboarded',
            name='sended_to_pz_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя дата отправки в ФАРМЗАКАЗ'),
        ),
    ]
