# Generated by Django 3.2.6 on 2022-06-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_branch_target_topic_to_send'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RateLimit',
        ),
    ]
