site_name: napari-threedee
site_description: A suite of useful tools based on 3D interactivity in napari
site_author: napari team

theme: readthedocs


repo_url: https://github.com/alisterburt/napari-threedee

pages:
- Home: index.md
