[tool.poetry]
name = "abandontech-siren"
version = "0.1.0"
description = "Async Python bindings for Minecraft's RCON protocol"
readme = "README.md"
repository = "https://github.com/AbandonTech/siren"
authors = ["fisher60 <kyler@abandontech.com>"]
license = "MIT"
packages = [
    { include = "siren.py" },
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
