[tool.poetry]
name = "idz"
version = "0.1.0"
description = ""
authors = ["k4w411p0wer <alexandrvasyutin@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
opencv-python = "^4.5.5"
opencv-contrib-python = "^4.5.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
