
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-13T09:58:16-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f071bba97b581d777be000596240078a7ccc2041",
 "version": "3.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
