
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-12T02:45:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cb6ecb1a22042d4a559b864e74c64d99352dcf7c",
 "version": "0.9.dev2224"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
