[tool.poetry]
name = "a62-emotion"
version = "0.9.4"
description = "A model for emotion classification based on text and audio."
authors = ["Philip Gaudreau <this@philipgaudreau.email>", "Guy Raymond <guy.tard@gmail.com>", "Gabriel Trottier <gtrottier16@gmail.com>"]
readme = "README.md"
repository = "https://github.com/philipgaudreau/emotion"

packages = [
    { include = "emotion"},
]

[tool.poetry.dependencies]
python = "~3.8"
keras = "^2.8.0"
numpy = "1.20.3"
scikit-learn = "0.24.2"
pandas = "1.2.4"
dvc = {version = "<2.11", extras = ["gdrive"]}

[tool.poetry.group.dev.dependencies]
nltk = "^3.7"
seaborn = "^0.11.2"
pytest = "^7.1.1"
jupyter = "^1.0.0"
pyAudioAnalysis = "^0.3.14"
ffmpy = "^0.3.0"
matplotlib = "3.4.2"
fanalysis = "^0.0.1"
TPOT = "^0.11.7"
torch = "^1.11.0"
wordcloud = "^1.8.1"

[tool.poetry.plugins."console_scripts"]
"emotion" = "emotion.cli:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
