defaults:
  - _default
  - config: classification
  - /model/eval: classification

_target_: ekorpkit.models.transformer.SimpleClassification
model_class: classification
labels: ${oc.select:dataset.labels, null}
num_labels:
use_cuda: true
cuda_device: -1
to_train:
  labels: ${..model.eval.to_eval.actual}
  text: text
to_predict:
  input: text
  predicted: ${..model.eval.to_eval.predicted}
  model_outputs: raw_preds
model:
  output_dir: ${..pred_output_dir}
  labels: ${..labels}
  eval:
    labels: ${..labels}
    to_eval:
      actual: labels
      predicted: pred_labels
      labels: ${..labels}
