defaults:
  - /io: _build_simple
  - /info: _build_dataset
  - /pipeline: _build_dataset

_target_: ekorpkit.corpora.build.DatasetBuilder
name:
category: general
data_dir: ${dir.dataset}/simple/${.name}
filetype: .csv
verbose: ${oc.select:..verbose, true}
autoload: true

normalize:
  preprocessor:
    normalizer: ${oc.select:dataset.simple.preprocessor.normalizer,null}
segment:
  preprocessor:
    segmenter: ${oc.select:dataset.simple.preprocessor.segmenter,null}
