version: 2

jobs:
  check-code-formatting:
    docker:
      - image: circleci/python:3.7.9

    steps:
      - checkout
      - run:
          name: Install black
          command: "sudo pip install -r requirements-dev.txt"
      - run:
          name: Check formatting with black
          command: "black --check ."

  python-3.6:
    docker:
      - image: circleci/python:3.6.9

    steps:
      - checkout
      - run:
          name: Install testing dependencies
          command: "sudo pip install -r requirements-dev.txt -r requirements.txt"
      - run:
          name: Test with pytest
          command: "pytest tests"

  python-3.9:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - run:
          name: Install testing dependencies
          command: "sudo pip install -r requirements-dev.txt -r requirements.txt"
      - run:
          name: Test with pytest
          command: "pytest tests"

workflows:
  version: 2
  code_formatting:
    jobs:
      - check-code-formatting
  build:
    jobs:
      - python-3.6
      - python-3.9
