[tool.poetry]
name = "pandakeeper"
version = "0.0.29"
description = "Python library designed to simplify the validation of dataset manipulations."
repository = "https://github.com/andrewsonin/pandakeeper"
homepage = "https://github.com/andrewsonin/pandakeeper"
authors = ["Andrew Sonin <sonin.cel@yandex.ru>"]
readme = "README.md"
license = "Apache License 2.0"

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1"
pandera = ">=0.9"
typing-extensions = ">=4"
varname = "^0.8"
varutils = "^0.0.8"

[tool.poetry.dev-dependencies]
ipython = "^7"
numpy = "~1.20"
pandas = "~1.1"
jupyter = "^1"
jupyterlab = "^3"
mypy = ">=0.950"
toml = "^0.10"
types-setuptools = "^57"
types-toml = "^0.10"
pandas-stubs = "^1"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=62", "toml>=0.10,<0.11"]
build-backend = "poetry.core.masonry.api"
