---
#
#  This file is part of NoCloud.Net.
#
#  Copyright (C) 2022 Last Bastion Network Pty Ltd
#
#  NoCloud.Net is free software: you can redistribute it and/or modify it under the
#  terms of the GNU General Public License as published by the Free Software
#  Foundation, either version 3 of the License, or (at your option) any later version.
#
#  NoCloud.Net is distributed in the hope that it will be useful, but WITHOUT ANY
#  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
#  PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with
#  NoCloud.Net. If not, see <https://www.gnu.org/licenses/>. 
#
default:
  DEBUG: false
  VENDOR_DATA: ''
  USER_DATA: ''
  SQLALCHEMY_TRACK_MODIFICATIONS: false
  DOMAIN: last-bastion.net
  INSTANCE_TYPE: mymachinetype
  # stevedore noclouddotnet.instanceid namespace value...
  INSTANCEID: reversedns
  
development:
  DEBUG: true
  SECRET_KEY: dev
  SQLALCHEMY_DATABASE_URI: 'sqlite:///nocloud.net.db'

test:
  DEBUG: true
  SQLALCHEMY_DATABASE_URI: 'sqlite:///:memory:'

production:
  SQLALCHEMY_DATABASE_URI: 'postgresql://user:password@localhost/nocloud'
  SECRET_KEY: prod
