[tool.poetry]
name = "binance_bigdata"
version = "0.1.0"
description = "Study of crypto currencies in python."
authors = ["Marc Partensky <marc.partensky@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
python-binance = "^1.0.16"
python-dotenv = "^0.20.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.14.1"
black = "^22.3.0"
neovim = "^0.3.1"
rich = "^12.4.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
