[tool.poetry]
name = "taktile-types"
version = "0.22.0"
description = ""
authors = ["Taktile GmbH <devops@taktile.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.6b0"
isort = "^5.9.1"
flake8 = "^3.9.2"
pylint = "^2.8.3"
mypy = "^0.910"
pyyaml = "^5.4.1"
flake8-print = "^4.0.0"
types-setuptools = "^57.4.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-version-plugin]
source = "init"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[tool.isort]
profile = "black"
line_length = 79

[tool.black]
line-length = 79
