version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.8  # Important for being able to import importlib.metadata
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs