[tool.poetry]
name = "clickset"
version = "0.1.0"
description = "In-class settings configurable via both click and confuse libraries\u001b"
authors = ["David Morris <gypsysoftware@gmail.com>"]
license = "MIT"
repository = "https://gitlab.com/selcouth/clickset"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
confuse = "^1.7.0"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
