[tool.poetry]
name = "fsai-coco-filter"
version = "0.1.1"
description = "Apply filters to a coco annotation file from a project configuration file."
authors = ["Michael Mohamed <michael@foundationstack.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/fsai-dev/fsai-coco-filter"
repository = "https://github.com/fsai-dev/fsai-coco-filter"

include = [
    "LICENSE",
]

[tool.poetry.scripts]
coco-filter = 'main:app'

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
loguru = "^=0.5.3"
echo1-coco-builder = "^0.1.8"
pydash = "^5.1.0"


[tool.poetry.dev-dependencies]
black = "^21.12b0"
pytest = ">=5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
'''