[tool.poetry]
name = "metacase"
version = "0.1.0"
description = "MetaCase is test case exporter tool based on FMF (Flexible Metadata Format) ."
authors = ["Fernando Giorgetti <fgiorget@redhat.com>", "Dominik Lenoch <dlenoch@redhat.com>"]
maintainers = ["Dominik Lenoch <dlenoch@redhat.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/enkeys/metacase/"
documentation = ""
keywords = [
    "fmf",
    "metadata",
    "test",
    "case",
    "jira"
]

[tool.poetry.dependencies]
python = "^3.9"
fmf = "^1.1.0"
jira = "^3.2.0"
urllib3 = "^1.26.9"
requests = "^2.28.0"

# Docs dependencies
myst-parser = {version = "^0.12.10", optional = true}
sphinx = {version = "^3.5.4", optional = true}
sphinx-autobuild = {version = "^2020.9.1", optional = true}
sphinx-rtd-theme = {version = "^0.5.2", optional = true}

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"

[tool.poetry.extras]
docs = [
    "myst-parser",
    "sphinx",
    "sphinx-autobuild",
    "sphinx-rtd-theme",
]

[tool.poetry.scripts]
metacase = 'metacase.metacase:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
    "pyproject.toml:version"
]
build_command = "pip install poetry && poetry build"

[tool.pytest.ini_options]
addopts = "-v -Wdefault --cov=metacase"
testpaths = [
    "tests"
]

[tool.coverage.run]
branch = true
source = ["fmfexport"]