[tool.poetry]
name = "spoti-dl"
version = "1.0.6"
description = "spotidl: download songs, albums and playlists using Spotify links"
authors = ["Dhruv"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/good-times-ahead/spoti-dl/"
repository = "https://github.com/good-times-ahead/spoti-dl/"
packages = [
    {include = "spotidl"}
]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
spotipy = "^2.19.0"
yt-dlp = "^2022.5.18"
python-dotenv = "^0.19.2"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"

[tool.poetry.dev-dependencies]
black = {version = "^21.12b0", allow-prereleases = true}
pylint = "^2.13.9"
pyfakefs = "^4.5.6"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
spotidl = "spotidl.main:cli"