[tool.poetry]
name = "twts"
version = "0.1.0"
description = "stream tweets from the terminal"
authors = ["redraw <redraw@sdf.org>"]

[tool.poetry.scripts]
twts = "twts.stream:cli"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.28.0"
tweepy = "^4.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
