[tool.poetry]
name = "aliby-post"
version = "0.1.27"
description = "Post-processing tools for aliby pipeline."
authors = ["Alán Muñoz <amuoz@ed.ac.uk>"]
license = "GPL-3.0-or-later"
packages = [
    { include = "postprocessor" },
]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
numpy = ">=1.17.3"
pandas = "^1.1.4"
scipy = ">=1.4.1"
PyYAML = "^6.0"
more-itertools = "^8.12.0"
catch22 = "^0.2.0"
leidenalg = "^0.8.8"
aliby-agora = "^0.2.28"
pathos = "^0.2.8"
seaborn = "^0.11.2"
scikit-learn = ">=0.22"
gaussianprocessderivatives = "^0.1.2"
p-tqdm = "^1.3.3"

[tool.poetry.dev-dependencies]
data-science-types = "^0.2.23"
black = "^22.3.0"
Sphinx = "^4.3.2"
pytest = "^6.2.5"
mypy = "^0.930"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
