name: pygeoutils-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  # async_retriever
  - aiodns
  - aiohttp>=3.8.1
  - aiohttp-client-cache>=0.5.1
  - aiosqlite
  - brotli
  - cchardet
  - cytoolz
  - importlib_metadata
  - ujson

  # pygeoogc deps
  - defusedxml
  - owslib
  - pydantic
  - pyyaml
  - pyproj>=1.2
  - requests
  - requests-cache>=0.8
  - shapely
  - urllib3

  # pygeoutils deps
  - dask-core
  - geopandas>=0.8
  - netcdf4
  - numpy>=1.17
  - pygeos
  - rasterio>=1.2
  - scipy
  - xarray>=0.18
  - rioxarray>=0.8

  # optional deps to speed up xarray
  - bottleneck

  # test deps
  - pytest-cov
  - pytest-xdist
  - psutil

  - pip
  - pip:
    - git+https://github.com/cheginit/async_retriever.git
    - git+https://github.com/cheginit/pygeoogc.git
