[tool.poetry]
name = "hereutil"
version = "0.1.0"
description = "Small utility to manage importing/sourcing python from under here()"
authors = ["Eetu Mäkelä <eetu.makela@iki.fi>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/hsci-r/hereutil"
keywords = [
    "here",
    "importing",
    "sourcing"
]

[tool.poetry.dependencies]
python = "^3.8"
pyprojroot = "^0.2.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.7"
pre-commit = "^2.13.0"
pylint = "^2.14.1"
Sphinx = "^4.2.0"
sphinx-rtd-theme = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

