# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: napari-threedee
author: Alister Burt and Kevin Yamauchi
#logo: images/logo.png

# Information about where the book exists on the web
repository:
  url: https://github.com/alisterburt/napari-threedee # Online location of your book
  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false

sphinx:
  extra_extensions:
    - sphinx.ext.viewcode
    - sphinx.ext.napoleon
    - sphinx.ext.autodoc
    - sphinx_autodoc_typehints
    - sphinx.ext.autosummary
    - sphinx.ext.intersphinx

  config:
    autosummary_generate: True
    autosummary_imported_members: True
    intersphinx_mapping:
      python:
        - "https://docs.python.org/3"
        - null
      numpy:
        - "https://numpy.org/doc/stable/"
        - null
