
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-09T13:20:16+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d3f5520f024348635e4c40c59119240109a56103",
 "version": "0.15.7a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
