name: Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_tox:
    name: tox -e ${{ matrix.toxenv }} (${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
        os:
          - "ubuntu-latest"
        toxenv:
          - "black"
          - "flake8"
          - "isort"
          - "mypy"
        include:
          - python-version: "3.8"
            os: "ubuntu-latest"
            toxenv: "py38"
          - python-version: "3.8"
            os: "ubuntu-latest"
            toxenv: "py38_extra"
          - python-version: "3.9"
            os: "ubuntu-latest"
            toxenv: "py39"
          - python-version: "3.9"
            os: "ubuntu-latest"
            toxenv: "py39_extra"
          - python-version: "3.10"
            os: "ubuntu-latest"
            toxenv: "py310"
          - python-version: "3.10"
            os: "ubuntu-latest"
            toxenv: "py310_extra"
          - python-version: "3.8"
            os: "macos-latest"
            toxenv: "py38_extra"
          - python-version: "3.9"
            os: "macos-latest"
            toxenv: "py39_extra"
          - python-version: "3.10"
            os: "macos-latest"
            toxenv: "py310_extra"
          - python-version: "3.8"
            os: "windows-latest"
            toxenv: "py38_extra"
          - python-version: "3.9"
            os: "windows-latest"
            toxenv: "py39_extra"
          - python-version: "3.10"
            os: "windows-latest"
            toxenv: "py310_extra"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U coverage setuptools tox wheel
          python --version
          pip --version
          tox --version
          coverage --version

      - name: Run tests
        run: tox -e ${{ matrix.toxenv }}
