# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kes.proto import project_pb2 as kes_dot_proto_dot_project__pb2


class ProjectStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.lookupProject = channel.unary_unary(
                '/kes.Project/lookupProject',
                request_serializer=kes_dot_proto_dot_project__pb2.LookupProjectRequest.SerializeToString,
                response_deserializer=kes_dot_proto_dot_project__pb2.LookupProjectReply.FromString,
                )
        self.readActivities = channel.unary_unary(
                '/kes.Project/readActivities',
                request_serializer=kes_dot_proto_dot_project__pb2.ReadActivitiesRequest.SerializeToString,
                response_deserializer=kes_dot_proto_dot_project__pb2.ReadActivitiesReply.FromString,
                )


class ProjectServicer(object):
    """Missing associated documentation comment in .proto file."""

    def lookupProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readActivities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProjectServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'lookupProject': grpc.unary_unary_rpc_method_handler(
                    servicer.lookupProject,
                    request_deserializer=kes_dot_proto_dot_project__pb2.LookupProjectRequest.FromString,
                    response_serializer=kes_dot_proto_dot_project__pb2.LookupProjectReply.SerializeToString,
            ),
            'readActivities': grpc.unary_unary_rpc_method_handler(
                    servicer.readActivities,
                    request_deserializer=kes_dot_proto_dot_project__pb2.ReadActivitiesRequest.FromString,
                    response_serializer=kes_dot_proto_dot_project__pb2.ReadActivitiesReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kes.Project', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Project(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def lookupProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kes.Project/lookupProject',
            kes_dot_proto_dot_project__pb2.LookupProjectRequest.SerializeToString,
            kes_dot_proto_dot_project__pb2.LookupProjectReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def readActivities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kes.Project/readActivities',
            kes_dot_proto_dot_project__pb2.ReadActivitiesRequest.SerializeToString,
            kes_dot_proto_dot_project__pb2.ReadActivitiesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
