# Generated by Django 3.2.6 on 2022-05-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_reconciliationresidue_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatusmap',
            name='status_one_c',
            field=models.SmallIntegerField(choices=[(1, 'Создан'), (2, 'Отдан на сборку'), (3, 'Принят складом'), (4, 'Подготовка к сборке'), (5, 'Отгружен'), (6, 'Доставлен'), (7, 'Частично доставлен'), (8, 'Расформирован'), (9, 'Консолидирован'), (10, 'Отказной'), (11, 'Не доставлен'), (12, 'Удален')], verbose_name='Статус заказа в 1С'),
        ),
    ]
