# Generated by Django 3.2.6 on 2022-05-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_orderstatusmap_status_one_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='target_topic_to_send',
            field=models.CharField(default='', max_length=255, verbose_name='Название филиала'),
            preserve_default=False,
        ),
    ]
