name: Test downstream projects

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: downstream-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ipykernel:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - uses: jupyterlab/maintainer-tools/.github/actions/downstream-test@v1
        with:
          package_name: ipykernel
          package_spec: "pyqt5 ipykernel[test]"

  nbclient:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - uses: jupyterlab/maintainer-tools/.github/actions/downstream-test@v1
        with:
          package_name: nbclient
          env_values: IPYKERNEL_CELL_NAME=\<IPY-INPUT\>

  nbconvert:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - uses: jupyterlab/maintainer-tools/.github/actions/downstream-test@v1
        with:
          package_name: nbconvert

  jupyter_server:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - uses: jupyterlab/maintainer-tools/.github/actions/downstream-test@v1
        with:
          package_name: jupyter_server

  jupyter_kernel_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Setup conda ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: jupyter_kernel_test
          miniforge-variant: Mambaforge
          python-version: ${{ matrix.python-version }}

      - name: Test jupyter_kernel_test
        shell: bash -l {0}
        run: |
          git clone https://github.com/jupyter/jupyter_kernel_test.git
          cd jupyter_kernel_test
          conda env update --name jupyter_kernel_test --file environment.yml
          conda install -c conda-forge xeus-cling
          pip install -e ".[test]"
          python -m unittest -v
