[tool.poetry]
name = "Obito"
version = "0.1.0"
description = "A URL file downloader that can download multiple files concurrently over internet."
authors = ["777advait"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/777advait/Obito"
repository = "https://github.com/777advait/Obito"
include = ["Obito/get_filesize.py"]

[tool.poetry.dependencies]
python = "^3.7"
typer = "^0.4.1"
rich = "^12.4.4"

[tool.poetry.scripts]
obito = "Obito.downloader:main"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/777advait/Obito/issues"