[project]
description = "A plugin for CPPython that enables vcpkg support for CMake projects"
name = "cppython-vcpkg"
license-expression = "MIT"
authors = [
    { name = "Synodic Software", email = "contact@synodic.software" },
]
readme = "README.md"
dynamic = []
requires-python = ">=3.10"
dependencies = [
    "cppython-core>=0.3.3.dev0",
]
version = "0.4.1.dev6"

[project.license-files]
paths = [
    "LICENSE.md",
]

[project.urls]
homepage = "https://github.com/Synodic-Software/CPPython-Vcpkg"
repository = "https://github.com/Synodic-Software/CPPython-Vcpkg"

[project.optional-dependencies]

[project.entry-points."cppython.generator"]
cmake = "cppython_vcpkg.plugin:VcpkgGenerator"

[tool.pdm.version]
use_scm = true

[tool.pdm.dev-dependencies]
lint = [
    "black>=22.3.0",
    "pylint>=2.13.8",
    "isort>=5.10.1",
]
test = [
    "pytest>=7.1.2",
    "pytest-cov>=3.0.0",
    "pytest-mock>=3.7.0",
    "pytest-cppython>=0.1.7.dev0",
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.black]
line-length = 120
preview = true

[tool.isort]
profile = "black"

[tool.pylint.messages_control]
disable = "C0330, C0326, logging-fstring-interpolation"
extension-pkg-whitelist = "pydantic"

[tool.pylint.format]
max-line-length = "120"

[build-system]
build-backend = "pdm.pep517.api"
requires = [
    "pdm-pep517",
]
