
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-09T13:11:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "de11409a267dd0b3c674cb1f5456d9d8002cc1a6",
 "version": "0.2.5.post0.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
