_target_: move.models.vae.VAE

# Use a custom resolver to extract the weights input in 'data/main.yaml'
categorical_names: ${names:${data.categorical_inputs}}
continuous_names: ${names:${data.continuous_inputs}}
categorical_weights: ${weights:${data.categorical_inputs}}
continuous_weights: ${weights:${data.continuous_inputs}}

num_hidden: 200
nLantent_04: 200
num_latent:
    - 150
    - 200
    - 250
    - 300
num_layers: 1
beta: 0.01
dropout: 0.2
batch_sizes: 10

cuda: ${training.cuda}
