[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'
[project]
name = 'span-cli'
version = '1.2.10'
dependencies = ['paramiko==2.11.0', 'requests==2.25.1', 'rich==12.4.1', 'scp==0.13.6', 'pyreadline==2.1;platform_system=="Windows"']
[project.scripts]
span = 'span.span:cli'