name: docker container

on: 
  push:
    branches: 
      - 'main'
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # - name: Fetch all history for all tags and branches
      #   run: git fetch --prune --unshallow

      - name: Setup docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # - name: Step to get tag name
      #   id: vars
      #   run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.NEAT
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/neat:latest
