[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pnlogger"
authors = [{name = "Pradeep", email = "nair.pradeep@gmail.com"}]
readme = "README.md"
classifiers = ["License :: OSI Approved :: Apache Software License"]
dynamic = ["version", "description"]
