[tool.poetry]
name = "cloudreactor-api-client"
version = "0.3.1.2"
description = "A client library for accessing the CloudReactor API, which monitors and manages Tasks and Workflows."

authors = [
    "Jeff Tsay <jeff@cloudreactor.io>"
]
license = "BSD 2-Clause"
readme = "README.md"
repository = "https://github.com/CloudReactor/cloudreactor-python-api-client/cloudreactor-api-client"
#documentation = "https://cloudreactor-procwrapper.readthedocs.io"
homepage = "https://cloudreactor.io"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
]

packages = [
    {include = "cloudreactor_api_client"},
]
include = ["CHANGELOG.md", "README-generated.md", "cloudreactor_api_client/py.typed"]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/CloudReactor/cloudreactor-python-api-client/issues"

[tool.poetry.dependencies]
python = "^3.7"
httpx = ">=0.15.4,<0.23.0"
attrs = ">=21.3.0"
python-dateutil = "^2.8.0"

[tool.poetry.dev-dependencies]
python-dotenv = ">=0.20.0"
flake8 = "^3.8.4"
isort = "^5.6.4"
pytest = "^6.2.1"
pytest-cov = "^2.10.1"
pytest-env = "^0.6.2"
tox = ">=3.25.0"
mypy = ">=0.942"
types-python-dateutil = "^2.8.14"

# Documentation Dependencies
Sphinx = {version = "^4.5.0", optional = true}
sphinx-rtd-theme = {version = "^1.0.0", optional = true}
myst-parser = {version = "^0.17.0", optional = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target_version = ['py37', 'py38', 'py39']
exclude = '''
(
  /(
    | \.git
    | \.venv
    | \.mypy_cache
  )/
)
'''

[tool.isort]
line_length = 120
profile = "black"

[tool.poetry.extras]
docs = [
    "myst-parser",
    "sphinx",
    "sphinx-rtd-theme",
]
