[build-system]
requires = ["setuptools>=62.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pisnp"
version = "2022.6.3"
description = "P is NP? (Polynomial is Non-polynomial?)"
readme = "README.md"
authors = [
    { name = "谢方圆 (XIE Fangyuan)", email = "xie.fangyuan@foxmail.com" }
]
license = { file = "LICENSE.txt" }
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]
keywords = [
    "polynomial",
    "non-polynomial",
]
dependencies = [
    "matplotlib",
    "numpy",
    "sty",
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "bumpver",
    "build",
    "twine",
]

[project.urls]
Homepage = "https://gitee.com/xie-fangyuan/pisnp"

[project.scripts]
realpython = "pisnp.__main__:main"

[tool.bumpver]
current_version = "2022.6.3"
version_pattern = "YYYY.MM.PATCH"
commit_message = "Bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"',
]
"README.md" = [
    "{version}",
]
"src/pisnp/__init__.py" = [
    "{version}",
]
