
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-07T17:31:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f6996bc1d977e4ed82e68c1b14682f24ee73494",
 "version": "0.2.4.post0.dev34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
