info = {"message": "Fix", "commit": "79ef977057aaeb9cecf5e85ce9a19be1afaf9ef0", "date": "2022-06-13 19:01:21 +0300", "branch": "fix/ff-again", "version": "1.4.1+237.g79ef9770.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
