[tool.poetry]
name = "keras-data-format-converter"
version = "0.0.13"
description = "Generates equal keras models with the desired data format"
readme = "README.md"
authors = ["dorhar <doron.harnoy@tensorleap.ai>"]

[tool.poetry.dependencies]
python = "^3.6.8"
tensorflow = "^2.6"
tensorflow-addons = "^0.16.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
