
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-13T11:15:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6834feac6dd3235fae99241d8ce5bc73ccf4c7ad",
 "version": "0.9.43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
