repos:
- repo: local
  hooks:
  - id: jupyter-clear-output
    name: jupyter-clear-output
    files: \.ipynb$
    stages: [commit]
    language: system
    entry: python3 -m nbconvert --ClearOutputPreprocessor.enabled=True --inplace
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black-jupyter
