[tool.poetry]
name = "jenova"
version = "0.1.0"
description = "Web framework built for learning purpose"
authors = ["Tobi-De <tobidegnon@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
gunicorn = "^20.1.0"
WebOb = "^1.8.7"
parse = "^1.19.0"
requests = "^2.27.1"
requests-wsgi-adapter = "^0.4.1"
Jinja2 = "^3.1.2"
whitenoise = "^6.2.0"
httpx = "^0.23.0"

[tool.poetry.dev-dependencies]
poetryup = "^0.7.2"
mypy = "^0.961"
black = "^22.3.0"
pre-commit = "^2.19.0"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
ipython = "^8.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
