
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-13T14:06:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "94c730bbcb3ff11e392c13f13499b63088fd10d5",
 "version": "0.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
