[project]
name = "a28"
dynamic = []
description = "A set of resources and tools to help developers create packages for the Area28 application."
authors = [
    { name = "Area28 Technologies", email = "dev@area28.io" },
]
requires-python = ">=3.7"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Natural Language :: English",
    "Environment :: Console :: Curses",
    "Environment :: X11 Applications :: Qt",
    "Intended Audience :: Developers",
]
dependencies = [
    "requests>=2.27.1",
    "certifi>=2022.5.18.1",
    "coloredlogs>=15.0.1",
]
version = "2.0.4"

[project.license]
text = "SEE LICENSE IN LICENSE"

[project.urls]
homepage = "https://github.com/area28technologies/devkit"
documentation = "https://area28technologies.github.io/devkit/"
repository = "https://github.com/area28technologies/devkit"
changelog = "https://github.com/area28technologies/devkit/blob/main/CHANGELOG.md"

[project.scripts]
a28 = "a28.cli:main"

[project.optional-dependencies]

[tool.flake8]
max-line-length = 79
max-doc-length = 72
max-complexity = 6
docstring-convention = "pep257"
show-source = true
ignore = [
    "S101",
    "PT012",
    "FS003",
]
exclude = [
    ".git",
    ".github",
    "__pycache__",
    "docs",
    "build",
    "dist",
    ".pytest_cache",
    "htmlcov",
]

[tool.pylint."MESSAGES CONTROL"]
enable = "all"

[tool.isort]
line_length = 79
include_trailing_comma = false
multi_line_output = 3
color_output = true
src_paths = [
    "src/a28",
    "tests",
]

[tool.pydocstyle]
convention = "pep257"

[tool.coverage.run]
source = [
    "src",
]

[tool.sphinx-pyproject]
github_username = "area28technologies"
github_repository = "devkit"
author = "Area28 Technologies"
project = "devkit"
copyright = "2022 Area28 Technologies"
language = "en"
master_doc = "index"
display_github = true
html_theme = "furo"
package_root = "src/a28"
html_static_path = [
    "_static",
]
confluence_publish = true
confluence_space_key = "CONFLUENCE_SPACE_KEY"
confluence_server_user = "CONFLUENCE_SERVER_USER"
onfluence_server_pass = "CONFLUENCE_SERVER_PASS"
confluence_server_url = "https://area28.atlassian.net/wiki/"
confluence_parent_page = "Documentation"
confluence_page_hierarchy = true
confluence_publish_dryrun = false
extensions = [
    "myst_parser",
    "sphinx.ext.napoleon",
    "sphinxarg.ext",
    "sphinx.ext.viewcode",
    "sphinx.ext.autodoc",
    "sphinxcontrib.confluencebuilder",
]
myst_enable_extensions = [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "html_admonition",
    "html_image",
    "replacements",
    "smartquotes",
    "strikethrough",
    "substitution",
    "tasklist",
]

[tool.sphinx-pyproject.html_theme_options]
sidebar_hide_name = true
announcement = "<em>RELEASE</em> version v2.0.0 released!"
light_logo = "assets/logo-light.svg"
dark_logo = "assets/logo-dark.svg"

[tool.sphinx-pyproject.html_theme_options.light_css_variables]
color-brand-primary = "#1F1B53"
color-brand-content = "#1F1B53"

[tool.pdm.version]
from = "src/a28/__version__.py"

[tool.pdm.scripts.lint]
cmd = "flake8 src tests"

[tool.pdm.scripts.test]
cmd = "pytest tests"

[tool.pdm.scripts.pre_document]
cmd = "sphinx-apidoc -f -o docs/src src/a28/"

[tool.pdm.scripts.document]
cmd = "sphinx-build docs/src docs/build"

[tool.pdm.scripts.confluence]
cmd = "sphinx-build -b confluence docs/src docs/build -E -a"

[tool.pdm.scripts.pre_coverage]
cmd = "pytest tests -qq --cov=a28 --cov-report=xml"

[tool.pdm.scripts.coverage]
cmd = "coverage report"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.1.2",
    "pytest-cov>=3.0.0",
    "pytest-httpserver>=1.0.4",
]
document = [
    "Sphinx>=4.5.0",
    "myst-parser>=0.17.2",
    "sphinx-pyproject>=0.1.0",
    "sphinx-argparse>=0.3.1",
    "invocations>=2.6.0",
    "furo>=2022.4.7",
    "sphinxcontrib-confluencebuilder>=1.8.0",
]
lint = [
    "flake9>=3.8.3.post2",
    "flake8-isort>=4.1.1",
    "flake8-bugbear>=22.4.25",
    "flake8-docstrings>=1.6.0",
    "flake8-bandit>=3.0.0",
    "flake8-pytest-style>=1.6.0",
    "flake8-quotes>=3.3.1",
    "flake8-pytest>=1.3",
    "flake8-use-fstring>=1.3",
    "pep8-naming>=0.11.1",
    "gitlint>=0.17.0",
    "setuptools>=62.2.0",
]

[build-system]
requires = [
    "pdm-pep517>=0.12.0",
]
build-backend = "pdm.pep517.api"
