[tool.poetry]
authors = ["Jan Gosmann <jan@hyper-world.de>"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Framework :: AsyncIO",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Topic :: Software Development :: Compilers",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
description = "Asynchronous parser taking incremental bites out of your byte input stream."
keywords = ["asyncio", "parser", "PEG", "incremental", "parser expression grammar"]
license = "MIT"
name = "bite-parser"
packages = [
  {include = "bite"},
]
readme = "README.rst"
repository = "https://github.com/jgosmann/bite-parser/"
version = "0.1.3"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
isort = "^5.6.4"
mypy = "^0.910"
pylint = "^2.6.0"
pytest = "^6.2.1"
pytest-asyncio = "^0.16.0"
pytest-cov = "^3.0.0"
typing-extensions = "^4.0.1"
Sphinx = "^4.4.0"
sphinx-rtd-theme = "^1.0.0"
darglint = "^1.8.1"

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
multi_line_output = 3
skip = [
  '.bzr',
  '.direnv',
  '.eggs',
  '.git',
  '.hg',
  '.mypy_cache',
  '.nox',
  '.pants.d',
  '.svn',
  '.tox',
  '.venv',
  '_build',
  'buck-out',
  'build',
  'dist',
  'node_modules',
  'venv',
]
use_parentheses = true

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
