name: CI

on: [push, pull_request]

jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        toxenv: [flake8, mypy, docs, black]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install tox
    - name: Run tox ${{ matrix.toxenv }}
      run: tox -e ${{ matrix.toxenv }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # required for setuptools_scm
    - name: Build sdist and temporary wheel
      run: pipx run build
    - uses: actions/upload-artifact@v2
      with:
        name: sdist
        path: dist/*.tar.gz

  test:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        include:
        - os: macos-latest
          python-version: 3.8
        - os: windows-latest
          python-version: 3.8
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox
      run: python -m pip install tox
    - name: Test
      run: tox -e py
    - name: Upload coverage report
      uses: codecov/codecov-action@v1

  wheels:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [lint, build, test]
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # required for setuptools_scm
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.1.2
      env:
        CIBW_BUILD: "cp*-manylinux_x86_64 cp3*-win_amd64"
        CIBW_ENVIRONMENT: "CFLAGS=-g0"
        CIBW_TEST_COMMAND: "cutadapt --help"
    - uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: wheelhouse/*.whl

  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [build, wheels]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: sdist
        path: dist/
    - uses: actions/download-artifact@v2
      with:
        name: wheels
        path: dist/
    - name: Publish dev release to test PyPI
      if: contains(github.ref, '.dev') || contains(github.ref, 'a')
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish to PyPI
      if: "!contains(github.ref, '.dev')"
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
