[tool.poetry]
name = "databaseci"
version = "5.8.2"
authors = [ "Robert Lechte <rob@databaseci.com>",]
license = "AGPL-3.0"
readme = "README.md"
description = "databaseci.com client"
classifiers = [
    "License :: OSI Approved :: GNU Affero General Public License v3"
]

homepage = "https://databaseci.com"

[tool.poetry.dependencies]
python = ">=3.8,<4"
migra = "*"
click = "*"
requests = "*"
pyyaml = "*"
py = "*"
psycopg2-binary = "*"
docker = "*"
pendulum = "*"
databaseciservices = ">=5.2.2"
schemainspect = ">=3.1.1648463413"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
flake8 = "*"
isort = "*"
mypy = "*"
black = "*"

[tool.poetry.scripts]
databaseci = 'databaseci:command.cli'

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
line_length = 88

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"
