defaults:
  - /_func_: save_dataframe

name: ${oc.select:..name, pipeline}
columns:
filepath:
filetype:
output_dir: ${oc.select:..output_dir, ${dir.output}/${.name}}
output_file: ${oc.select:..output_file, ${.name}.${.filetype}}
verbose: ${oc.select:..verbose, true}
