# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cegalprizm/hub/agent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cegalprizm/hub/agent.proto',
  package='hub',
  syntax='proto3',
  serialized_options=b'Z\007./agent',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x63\x65galprizm/hub/agent.proto\x12\x03hub\"\x9d\x01\n\x10ListFilesRequest\x12\x11\n\troot_path\x18\x01 \x01(\t\x12\x11\n\trecursive\x18\x02 \x01(\x08\x12\x0e\n\x06suffix\x18\x03 \x01(\t\x12\x1f\n\x17skip_folder_starts_with\x18\x04 \x03(\t\x12\x1c\n\x14skip_folder_contains\x18\x05 \x03(\t\x12\x14\n\x0ctimeout_secs\x18\x06 \x01(\x05\"~\n\x0fListFilesResult\x12\r\n\x05paths\x18\x01 \x03(\t\x12\x19\n\x11num_dirs_searched\x18\x02 \x01(\x03\x12\x18\n\x10num_dirs_skipped\x18\x03 \x01(\x03\x12\x12\n\nnum_errors\x18\x04 \x01(\x03\x12\x13\n\x0bnum_results\x18\x05 \x01(\x03\"\xc9\x01\n\x18LaunchApplicationRequest\x12\x14\n\x0cprofile_name\x18\x01 \x01(\t\x12\x18\n\x10\x65nv_var_override\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x03(\t\x12\x1d\n\x15override_default_args\x18\x04 \x01(\x08\x12\x18\n\x10is_hub_connector\x18\x05 \x01(\x08\x12\x18\n\x10wait_for_connect\x18\x06 \x01(\x08\x12\x1c\n\x14\x63onnect_timeout_secs\x18\x07 \x01(\x05\"C\n\x17LaunchApplicationResult\x12\x12\n\nprocess_id\x18\x01 \x01(\x05\x12\x14\n\x0c\x63onnector_id\x18\x02 \x01(\tB\tZ\x07./agentb\x06proto3'
)




_LISTFILESREQUEST = _descriptor.Descriptor(
  name='ListFilesRequest',
  full_name='hub.ListFilesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='root_path', full_name='hub.ListFilesRequest.root_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recursive', full_name='hub.ListFilesRequest.recursive', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='suffix', full_name='hub.ListFilesRequest.suffix', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skip_folder_starts_with', full_name='hub.ListFilesRequest.skip_folder_starts_with', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skip_folder_contains', full_name='hub.ListFilesRequest.skip_folder_contains', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeout_secs', full_name='hub.ListFilesRequest.timeout_secs', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=193,
)


_LISTFILESRESULT = _descriptor.Descriptor(
  name='ListFilesResult',
  full_name='hub.ListFilesResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='paths', full_name='hub.ListFilesResult.paths', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_dirs_searched', full_name='hub.ListFilesResult.num_dirs_searched', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_dirs_skipped', full_name='hub.ListFilesResult.num_dirs_skipped', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_errors', full_name='hub.ListFilesResult.num_errors', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_results', full_name='hub.ListFilesResult.num_results', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=321,
)


_LAUNCHAPPLICATIONREQUEST = _descriptor.Descriptor(
  name='LaunchApplicationRequest',
  full_name='hub.LaunchApplicationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile_name', full_name='hub.LaunchApplicationRequest.profile_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='env_var_override', full_name='hub.LaunchApplicationRequest.env_var_override', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='args', full_name='hub.LaunchApplicationRequest.args', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='override_default_args', full_name='hub.LaunchApplicationRequest.override_default_args', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_hub_connector', full_name='hub.LaunchApplicationRequest.is_hub_connector', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wait_for_connect', full_name='hub.LaunchApplicationRequest.wait_for_connect', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connect_timeout_secs', full_name='hub.LaunchApplicationRequest.connect_timeout_secs', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=525,
)


_LAUNCHAPPLICATIONRESULT = _descriptor.Descriptor(
  name='LaunchApplicationResult',
  full_name='hub.LaunchApplicationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='process_id', full_name='hub.LaunchApplicationResult.process_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connector_id', full_name='hub.LaunchApplicationResult.connector_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=594,
)

DESCRIPTOR.message_types_by_name['ListFilesRequest'] = _LISTFILESREQUEST
DESCRIPTOR.message_types_by_name['ListFilesResult'] = _LISTFILESRESULT
DESCRIPTOR.message_types_by_name['LaunchApplicationRequest'] = _LAUNCHAPPLICATIONREQUEST
DESCRIPTOR.message_types_by_name['LaunchApplicationResult'] = _LAUNCHAPPLICATIONRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListFilesRequest = _reflection.GeneratedProtocolMessageType('ListFilesRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTFILESREQUEST,
  '__module__' : 'cegalprizm.hub.agent_pb2'
  # @@protoc_insertion_point(class_scope:hub.ListFilesRequest)
  })
_sym_db.RegisterMessage(ListFilesRequest)

ListFilesResult = _reflection.GeneratedProtocolMessageType('ListFilesResult', (_message.Message,), {
  'DESCRIPTOR' : _LISTFILESRESULT,
  '__module__' : 'cegalprizm.hub.agent_pb2'
  # @@protoc_insertion_point(class_scope:hub.ListFilesResult)
  })
_sym_db.RegisterMessage(ListFilesResult)

LaunchApplicationRequest = _reflection.GeneratedProtocolMessageType('LaunchApplicationRequest', (_message.Message,), {
  'DESCRIPTOR' : _LAUNCHAPPLICATIONREQUEST,
  '__module__' : 'cegalprizm.hub.agent_pb2'
  # @@protoc_insertion_point(class_scope:hub.LaunchApplicationRequest)
  })
_sym_db.RegisterMessage(LaunchApplicationRequest)

LaunchApplicationResult = _reflection.GeneratedProtocolMessageType('LaunchApplicationResult', (_message.Message,), {
  'DESCRIPTOR' : _LAUNCHAPPLICATIONRESULT,
  '__module__' : 'cegalprizm.hub.agent_pb2'
  # @@protoc_insertion_point(class_scope:hub.LaunchApplicationResult)
  })
_sym_db.RegisterMessage(LaunchApplicationResult)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
