
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-08T17:08:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "844fe1df16b8380bd4e7ee8cec0ee5ca848593c6",
 "version": "2.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
