[tool.poetry]
name = "jupyterlab-lsf"
version = "0.1.0"
description = "📙 Run jupyter lab in an LSF host and map its port"
authors = ["Juanes <juanes.ao@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0.4"
jupyterlab = "^3.2.9"

[tool.poetry.dev-dependencies]
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
