
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-11T20:40:22-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f81ca6ce260ae0f4204c1d6d185e32a1fa2ac03",
 "version": "0.0.107"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
