[tool.poetry]
name = "django3-registration"
version = "2.6.0"
description = "An extensible user-registration application for Django"
homepage = "https://github.com/ImaginaryLandscape/django3-registration"
readme = "README.rst"
authors = ["James Bennett <james@b-list.org>"]
maintainers = ["Imagescape <info@imagescape.com>"]
license = "BSD"
packages = [
    { include = "registration" },
]

[tool.poetry.dependencies]
python = "^3.6"
confusable_homoglyphs = "~=3.0"
Django = "^3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
