name: async_retriever-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  - aiodns
  - aiohttp>=3.8.1
  - aiohttp-client-cache>=0.5.1
  - aiosqlite
  - brotli
  - cchardet
  - cytoolz
  - importlib_metadata
  - ujson

  - pytest-cov
  - pytest-xdist
  - psutil
