"""Module containing package information for setup.py and __init__.py"""
__title__ = "eumdac"
__description__ = "EUMETSAT Data Access Client"
__url__ = "https://gitlab.eumetsat.int/eumetlab/data-services/eumdac"
__version__ = "1.1.0"
__author__ = "EUMETSAT"
__author_email__ = "ops@eumetsat.int"
__license__ = "MIT"
