# for atmospheric muon bundles, mupage ORCA4, graph network
mode = "graph"
extractor = "bundle_mc"
time_window = [-250, 1000]

[extractor_config]
inactive_du = 1
plane_point = [17, 17, 111]
only_downgoing_tracks = true
