[tool.poetry]
name = "web-youtube-dl"
version = "0.2.0"
description = "A web version of youtube-dl"
readme = "README.rst"
authors = ["Uriel Mandujano <uriel.mandujano14@gmail.com>"]
classifiers = [
    "Topic :: Home Automation",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Multimedia :: Sound/Audio :: Capture/Recording",
]


[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0"
uvicorn = "^0.17.0"
python-multipart = "^0.0.5"
aiofiles = "^0.5.0"
janus = "^0.5.0"
Werkzeug = "^1.0.1"
pytube = "^12.0.0"
Jinja2 = "^3.1.2"
websockets = "^10.3"
ffmpeg-python = "^0.2.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
mypy = "^0.960"
pytest-cov = "^2.10.1"
requests = "^2.24.0"
black = "^22.3.0"
isort = "^5.10.1"

[tool.isort]
profile = "black"
src_paths = ["web_youtube_dl", "tests"]

[tool.poetry.scripts]
web-youtube-dl-cli = "web_youtube_dl.app.main:cli_download"
web-youtube-dl-web = "web_youtube_dl.app.main:run_app"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

