version: 1
formatters:
  default:
    format: "[%(levelname)s][%(asctime)s][%(module)s]: %(message)s"
  json:
    '()': uw_it.flask_util.logger.JsonFormatter
handlers:
  wsgi:
    level: INFO
    class: logging.StreamHandler
    formatter: json
  gunicorn:
    level: ERROR
    class: logging.StreamHandler
    formatter: default
loggers:
  glogging:
    # Turn off all but critical `glogging` messages, because it's
    # a very noisy module that is out of our control.
    level: CRITICAL
    propagate: false
  gunicorn.error.app:
    level: DEBUG
    propagate: false
    handlers:
      - wsgi
  gunicorn.error:
    handlers:
      - gunicorn
  gunicorn.error.app.unscoped:
    handlers:
      - gunicorn
